image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [2349.67798,    0.     ,  702.41122,
            0.     , 2346.87502,  545.3651 ,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.098581, 0.101100, -0.000111, -0.001019, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2333.60002,    0.     ,  702.66364,    0.     ,
            0.     , 2336.20724,  545.61774,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]