camera: 
  hik_a:
    odom2camera_a:
      xyz: "\"0.08 0.065  0.045\""
      rpy: "\"0.0  -0.00351  -0.0021\""  #0.0245

detector_log_level: INFO # INFO
tracker_log_level: WARN
serial_log_level: INFO

camera: 
  hik_b:
    odom2camera_b:
      xyz: "\"0.08 0.065  0.045\""
      rpy: "\"0.0  -0.00351  -0.0021\""  #0.0245

detector_log_level: INFO # INFO
tracker_log_level: WARN
serial_log_level: INFO
